# Site settings
author: Devon Wright
title: My journey to Developing
header-img: img/home-bg.png
email: devonjamess.wright@gmail.com
copyright_name: Devon Wright
description: > # this means to ignore newlines until "baseurl:"
  (I totally know what I'm doing)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DevonJamesWright

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
